### ISSUE TITLE
I can't get pass the warning screen even if i click severaltimes i even tried clicking buttons but it still won't work

### ISSUE THREAD

**Issue by BadNewsBurgers** [Fasguy/BaldisBasicsModMenu-archive#19]
I'm using version Baldi's Basics 1.4.3
The Mod version is 2.0.2
I'm using Windows 10 64-bit

**Comment by Fasguy** [comment]
Either you're not actually using the game/mod version you think you're using, or the mod got corrupted somehow.
If it's the latter, then simply re-downloading the mod should fix the issue.

**Comment by BadNewsBurgers** [comment]
yea i think the mod got corrupted i dont really know what happened i even checked the mod and game versions and they were the the right version

i also tried redownloading it but still dosent work

**Comment by Fasguy** [comment]
Unfortunately, there isn't much else i can use to debug this, as the Classic version of Baldi's Basics doesn't actually create a log file anymore, as far as i know.

**Comment by poppyplaytimefan** [comment]
Normal baldi's basics 1.4.3 also does not work

**Comment by poppyplaytimefan** [comment]
If there is any more versions coming to the mod menu please try fix this because not only does it not work on normal Baldi 1.4.3 but it also doesent work on ANY mods (I think)

**Comment by Fasguy** [comment]
There isn't really much i can actually do to fix this, because every time this error has occured it was user error.

One of these has always been the culprit:
* Trying to combine incompatible mod/game versions (Mod Menu v1.11 into Game v1.2.2 for example)
* Trying to combine incompatible mod/game types (Mod Menu for Birthday Bash into Baldi's Basics Classic for example)
* Aborted the download of either the game or the mod ins ome way, shape or form, therefore corrupting either the game or the mod
