### ISSUE TITLE
Potential virus?

### ISSUE THREAD

**Issue by EpicMario5345** [Fasguy/BaldisBasicsModMenu-archive#21]
(Re-uploaded from another area where I sent it)
So, I don't know if this was said before, but scanning the Android versions of your mod menus for Baldi's Basics in VirusTotal came up with some surprising results.
Older versions has adware and password loggers, while the most recent version has literal malware.

I need confirmation that this isn't the case.

Things that show up (in recent version):
Android.Riskware.TaJawaBar.A
Trojan.Malware.300983.susgen

**Comment by Fasguy** [comment]
I don't know exactly what causes certain AVs to detect the ModMenu as malicious. My best guess is that the signature i had to use for signing the APK is no longer trusted.
But i honestly don't really care, because [a re-scan of a completely unmodified APK of BB Classic is also detected as malicious.](https://www.virustotal.com/gui/file/0c6fbd228632f101b4e149387fb9b439a3c32efc6c68d800167dc07144b1cc58/detection)

As for you needing "confirmation that this isn't the case": You probably shouldn't ask the person who's trying to get you to download the file. If i genuinely had malicious intent, then nothing would stop me from just lying to you.

**Comment by Fasguy** [comment]
For good measure i did actually do some investigating on this.

* **Trojan.Malware.300983.susgen** is actually triggered by [UnityEngine.ParticleSystemModule.dll](https://www.virustotal.com/gui/file/eab07b11c8608fe699f2cf6793b6aa72ea558db07905e43cbf79cf7bb49cfcf6). [This can be seen on the "Relations" page on Virustotal](https://www.virustotal.com/gui/file/17c9a469825cb85db411df30c05208c0f76626c72e08784ee35880db0be1a1f3/relations). This file is a fully unmodified Unity file.
* **Android.Riskware.TaJawaBar.A** is (as i suspected) triggered by the signature i used to sign the APK.
![image](https://user-images.githubusercontent.com/9297451/198699685-bcdfae18-455c-49bc-a0b6-03ba9469479e.png)
[This can be seen on the "Details" page on Virustotal](https://www.virustotal.com/gui/file/17c9a469825cb85db411df30c05208c0f76626c72e08784ee35880db0be1a1f3/details).
