### ISSUE TITLE
Force the critical error screen to appear upon death

### ISSUE THREAD

**Issue by Neopolaria** [Fasguy/BaldisBasicsModMenu-archive#45]
**Why do you need this feature?**
-I think it would be a neat thing to be able to modify the chance of it happening, guarantee it happening, all without having to die to baldi several times if that could be added please

**Describe the feature**
-[The rare death screen](https://youtu.be/CABbIKyIIwI) has a 1% chance of happening, and I think its a neat feature that I like to come back to from time to time but I keep having to die to Baldi hundreds of times to trigger it. There should be a feature that allows one to modify the chance of it happening or guarantee it, like game modifiers -> rare screen -> modify percentage/guarantee. It could also be added to the scene manager if that is easier. Thank you!

**Comment by Fasguy** [comment]
Just to clarify something, the death screen does *not* have a set 1% of appearing. The chance adjusts depending on how long it's been since the screen has appeared last time.

I'd probably just add this as a generic option, that forces the screen to appear upon death by Baldi, as well as adding an option that forces the game to move back to the title screen, instead of force-closing it.

**Comment by Neopolaria** [comment]
Interesting, I wasn't aware the chance would change. Thank you!
